### ISSUE TITLE
Could not load 'plugins/firstplugin.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by BlendyCat** [BlendyCat/MyWarp#1]
```
org.bukkit.plugin.InvalidPluginException: Cannot find main class `com.blendycat.mywarps.Main'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:66) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot.jar:git-Spigot-de459a2-51263e9]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: com.blendycat.mywarps.Main
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_51]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	... 7 more

```
Error loading

**Comment by BlendyCat** [comment]
Seems to be way I initialized the commands. Maybe doing it in multiple classes wasn't the best idea after all.
